template
"""
FinLegal-Chat Ultimate - Document Automation Engine
Generates professional Word, Excel, and PDF reports.
"""

import os
from datetime import datetime
from typing import Dict, Optional, List, Any
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.utils import get_column_letter


class DocumentAutomator:
    """
    Professional document generation for legal and financial reports.
    Supports Word (.docx), Excel (.xlsx) with styled charts.
    """

    # Brand colors
    GOLD = RGBColor(0xD4, 0xA8, 0x43)
    DARK_NAVY = RGBColor(0x0A, 0x0E, 0x27)
    DARK_BLUE = RGBColor(0x12, 0x18, 0x3B)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    LIGHT_GRAY = RGBColor(0x94, 0xA3, 0xB8)
    DARK_TEXT = RGBColor(0x1E, 0x29, 0x3B)

    @staticmethod
    def _set_cell_shading(cell, color_hex: str):
        """Set cell background color."""
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        shading = OxmlElement('w:shd')
        shading.set(qn('w:fill'), color_hex)
        shading.set(qn('w:val'), 'clear')
        cell._tc.get_or_add_tcPr().append(shading)

    def create_legal_report(self, title: str, content: Dict[str, str], output_path: str):
        """
        Generate a professionally styled Word document report.
        
        Args:
            title: Report title
            content: Dict of {section_title: section_text}
            output_path: Output file path
        """
        doc = Document()

        # --- Page Setup ---
        section = doc.sections[0]
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

        # --- Styles ---
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Calibri'
        font.size = Pt(11)
        font.color.rgb = self.DARK_TEXT
        style.paragraph_format.space_after = Pt(6)
        style.paragraph_format.line_spacing = 1.15

        # --- Cover Page ---
        # Add spacer
        for _ in range(6):
            doc.add_paragraph()

        # Title
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title_para.add_run(title)
        run.font.size = Pt(28)
        run.font.color.rgb = self.GOLD
        run.bold = True
        run.font.name = 'Calibri Light'

        # Divider line
        divider = doc.add_paragraph()
        divider.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = divider.add_run('_' * 60)
        run.font.color.rgb = self.GOLD
        run.font.size = Pt(12)

        # Subtitle
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run('Generated by FinLegal-Chat Ultimate AI Engine')
        run.font.size = Pt(12)
        run.font.color.rgb = self.LIGHT_GRAY
        run.font.name = 'Calibri Light'

        # Date
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = date_para.add_run(datetime.now().strftime('%B %d, %Y - %H:%M'))
        run.font.size = Pt(11)
        run.font.color.rgb = self.LIGHT_GRAY

        # Page break
        doc.add_page_break()

        # --- Table of Contents ---
        toc_heading = doc.add_heading('Table of Contents', level=1)
        for run in toc_heading.runs:
            run.font.color.rgb = self.GOLD
            run.font.name = 'Calibri Light'

        for i, section_title in enumerate(content.keys(), 1):
            toc_item = doc.add_paragraph()
            toc_item.paragraph_format.space_after = Pt(4)
            run = toc_item.add_run(f'{i}.  {section_title}')
            run.font.size = Pt(11)
            run.font.color.rgb = self.DARK_TEXT

        doc.add_page_break()

        # --- Content Sections ---
        for idx, (section_title, section_text) in enumerate(content.items(), 1):
            # Section heading
            heading = doc.add_heading(f'{idx}. {section_title}', level=2)
            for run in heading.runs:
                run.font.color.rgb = self.DARK_NAVY
                run.font.name = 'Calibri Light'

            # Section body
            if section_text:
                # Split into paragraphs
                paragraphs = section_text.split('\n\n')
                for para_text in paragraphs:
                    para_text = para_text.strip()
                    if not para_text:
                        continue
                    p = doc.add_paragraph()
                    p.paragraph_format.space_after = Pt(8)
                    p.paragraph_format.first_line_indent = Cm(0.75)
                    run = p.add_run(para_text)
                    run.font.size = Pt(11)
                    run.font.color.rgb = self.DARK_TEXT

            # Add separator between sections (except last)
            if idx < len(content):
                sep = doc.add_paragraph()
                sep.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = sep.add_run('- ' * 30)
                run.font.color.rgb = RGBColor(0xE2, 0xE8, 0xF0)
                run.font.size = Pt(8)

        # --- Footer ---
        footer_text = doc.add_paragraph()
        footer_text.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer_text.add_run(
            f'Confidential - FinLegal-Chat Ultimate | Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}'
        )
        run.font.size = Pt(9)
        run.font.color.rgb = self.LIGHT_GRAY
        run.italic = True

        doc.save(output_path)
        return output_path

    def create_financial_spreadsheet(self, data: Dict, output_path: str):
        """
        Generate a professionally styled Excel spreadsheet with chart.
        
        Args:
            data: Dict with 'labels', 'values', and optional 'title'
            output_path: Output file path
        """
        wb = Workbook()
        ws = wb.active
        ws.title = 'Financial Analysis'

        # --- Styles ---
        header_font = Font(name='Calibri', size=12, bold=True, color='FFFFFF')
        header_fill = PatternFill(start_color='0D1B2A', end_color='0D1B2A', fill_type='solid')
        data_font = Font(name='Calibri', size=11)
        gold_fill = PatternFill(start_color='D4A843', end_color='D4A843', fill_type='solid')
        alt_fill = PatternFill(start_color='F8FAFC', end_color='F8FAFC', fill_type='solid')
        thin_border = Border(
            left=Side(style='thin', color='E2E8F0'),
            right=Side(style='thin', color='E2E8F0'),
            top=Side(style='thin', color='E2E8F0'),
            bottom=Side(style='thin', color='E2E8F0'),
        )
        center_align = Alignment(horizontal='center', vertical='center')
        left_align = Alignment(horizontal='left', vertical='center')

        # --- Title Row ---
        title = data.get('title', 'Financial Data Analysis')
        ws.merge_cells('A1:B1')
        cell = ws['A1']
        cell.value = title
        cell.font = Font(name='Calibri Light', size=16, bold=True, color='D4A843')
        cell.alignment = Alignment(horizontal='center', vertical='center')
        ws.row_dimensions[1].height = 40

        # --- Meta Info ---
        ws.merge_cells('A2:B2')
        ws['A2'].value = f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}'
        ws['A2'].font = Font(name='Calibri', size=10, color='94A3B8', italic=True)
        ws['A2'].alignment = Alignment(horizontal='center')

        # --- Header Row ---
        row = 4
        ws.cell(row=row, column=1, value='Category').font = header_font
        ws.cell(row=row, column=1).fill = header_fill
        ws.cell(row=row, column=1).alignment = center_align
        ws.cell(row=row, column=1).border = thin_border

        ws.cell(row=row, column=2, value='Value').font = header_font
        ws.cell(row=row, column=2).fill = header_fill
        ws.cell(row=row, column=2).alignment = center_align
        ws.cell(row=row, column=2).border = thin_border

        ws.row_dimensions[row].height = 30

        # --- Data Rows ---
        labels = data.get('labels', [])
        values = data.get('values', [])

        for i, (label, value) in enumerate(zip(labels, values)):
            r = row + 1 + i
            ws.cell(row=r, column=1, value=label)
            ws.cell(row=r, column=1).font = Font(name='Calibri', size=11, bold=True)
            ws.cell(row=r, column=1).alignment = left_align
            ws.cell(row=r, column=1).border = thin_border

            ws.cell(row=r, column=2, value=value)
            ws.cell(row=r, column=2).font = data_font
            ws.cell(row=r, column=2).alignment = center_align
            ws.cell(row=r, column=2).border = thin_border
            ws.cell(row=r, column=2).number_format = '#,##0.00'

            # Alternate row coloring
            if i % 2 == 1:
                ws.cell(row=r, column=1).fill = alt_fill
                ws.cell(row=r, column=2).fill = alt_fill

        # --- Add Chart ---
        if labels and values:
            chart_type = data.get('type', 'bar')
            if chart_type == 'line':
                chart = LineChart()
                chart.title = title
                chart.style = 10
                chart.y_axis.title = 'Value'
            else:
                chart = BarChart()
                chart.title = title
                chart.style = 10
                chart.y_axis.title = 'Value'

            chart.width = 18
            chart.height = 12

            data_ref = Reference(ws, min_col=2, min_row=row, max_row=row + len(labels))
            cats_ref = Reference(ws, min_col=1, min_row=row + 1, max_row=row + len(labels))

            chart.add_data(data_ref, titles_from_data=True)
            chart.set_categories(cats_ref)

            # Style the chart series
            if chart.series:
                series = chart.series[0]
                series.graphicalProperties.solidFill = 'D4A843'

            chart_row = row + len(labels) + 3
            ws.add_chart(chart, f'A{chart_row}')

        # --- Column Widths ---
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 18

        # --- Freeze Panes ---
        ws.freeze_panes = 'A5'

        # --- Print Setup ---
        ws.print_title_rows = '4:4'
        ws.sheet_properties.pageSetUpPr.fitToPage = True

        wb.save(output_path)
        return output_path

    @staticmethod
    def create_summary_text(report_data: Dict[str, str], max_chars: int = 500) -> str:
        """Create a plain text summary of a report."""
        parts = []
        for section, text in report_data.items():
            if text:
                truncated = text[:max_chars]
                if len(text) > max_chars:
                    truncated += '...'
                parts.append(f"{section}:\n{truncated}")
        return '\n\n'.join(parts)
